django/cookiecutters/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.contrib import admin
from projects.views import LanguageListView


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', LanguageListView.as_view()),
)

django/cookiecutters/projects/models.py
# coding: utf-8
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext as _


class Language(models.Model):
    name = models.CharField(_('name'), max_length=32)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name


class Project(models.Model):
    language = models.ForeignKey(Language, verbose_name=_('language'))
    name = models.CharField(_('name'), max_length=64)
    author = models.CharField(_('author'), max_length=64)
    repository_url = models.CharField(_('repository URL'), max_length=64)
    description = models.TextField(_('description'))
    created_at = models.DateTimeField(_('created at'), default=now)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

django/cookiecutters/templates/models.py
# coding: utf-8
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext as _


class Language(models.Model):
    name = models.CharField(_('name'), max_length=32)

    def __unicode__(self):
        return self.name


class Template(models.Model):
    language = models.ForeignKey(Language, verbose_name=_('language'))
    name = models.CharField(_('name'), max_length=64)
    author = models.CharField(_('author'), max_length=64)
    repository_url = models.CharField(_('author'), max_length=64)
    description = models.TextField(_('description'))
    created_at = models.DateTimeField(_('created at'), default=now)

    def __unicode__(self):
        return self.name

django/cookiecutters/projects/views.py
# coding: utf-8
from django.views.generic import ListView
from models import Language


class LanguageListView(ListView):
    queryset = Language.objects.all()
    template_name = 'projects/project_list.html'

django/cookiecutters/templates/views.py
# coding: utf-8
from django.views.generic import ListView
from models import Language


class LanguageListView(ListView):
    queryset = Language.objects.all()
    template_name = 'templates/template_list.html'

django/cookiecutters/projects/templates/projects/project_list.html
{% extends "base.html" %}

{% block content %}
    {% for language in object_list %}
        <div class="language-header">
            <h3>{{ language.name }}</h3>
        </div>
        {% with language.project_set.all as projects %}
            {% if projects %}
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Author</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td class="col-name"><a target="_blank" href="{{ project.repository_url }}">{{ project.name }}</a></td>
                                <td>{{ project.description }}</td>
                                <td><a href="http://github.com/{{ project.author }}">{{ project.author }}</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>

                </table>
            {% endif %}
        {% endwith %}
    {% endfor %}

{% endblock content %}

django/cookiecutters/templates/base.html
<html>
  <head>
    <title>cookiecutters.cc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{{ STATIC_URL}}css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{ STATIC_URL}}css/cookiecutters.css" rel="stylesheet" media="screen">
  </head>

  <body>
    <nav class="navbar-wrapper navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">cookiecutters</a>
        </div>

        {% comment %}
        <div class="collapse navbar-collapse navbar-ex1-collapse">
        <div class="collapse navbar-collapse">
        <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Ok</button>
        </form>
        </div>
        {% endcomment %}

      </div>
    </nav>

    <div class="container">
      <div class="row">
        Here are all the cookiecutters we've found yet, contribute submitting yours!

        {% block content %}

        {% endblock content %}
      </div>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          cookicutter is a tool developed by @audreyr
        </div>
      </div>
    </footer>

    <!-- submit -->
    <div id="submit-modal" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Submit a cookiecutter</h4>
          </div>

          <div class="modal-body">
            <p>You don't need to be the author to submit, just fill the form below:</p>

            <form class="form-horizontal" role="form">
              <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Your e-mail</label>
                <div class="col-sm-10">
                  <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                </div>
                <p class="help-block">We'll notify you when it gets approved</p>
              </div>

              <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Project name</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="inputEmail3" placeholder="Example: cookiecutter-django">
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox"> Remember me
                    </label>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-default">Sign in</button>
                </div>
              </div>
            </form>
          </div>


          <div class="modal-footer">
            <button type="button" class="btn btn-primary">Submit</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <script src="{{ STATIC_URL}}js/jquery.min.js"></script>
    <script src="{{ STATIC_URL}}js/bootstrap.min.js"></script>
  </body>
</html>

django/cookiecutters/templates/templates/templates/template_list.html
{% for language in object_list %}
    <li>
        {{ language.name }}
        {% with language.template_set.all as templates %}
            {% if templates %}
                <ul>
                    {% for template in templates %}
                        <li>{{ template.name }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
    </li>
{% endfor %}